global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "datak-gateway"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metrics_path: "/metrics"

  - job_name: "influxdb"
    static_configs:
      - targets: ["influxdb:8086"]
    metrics_path: "/metrics"
